---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
  labels:
    db: mariadb
  name: mariadb
spec:
  replicas: 1
  revisionHistoryLimit: 2
  serviceName: "mariadb"
  selector:
    matchLabels:
        db: mariadb
  template:
    metadata:
      annotations:
      labels:
        db: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom: 
            configMapKeyRef:
              name: spring-app
              key: SPRING_DATASOURCE_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: spring-app
              key: SPRING_DATASOURCE_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: spring-app
              key: SPRING_DATASOURCE_PASSWORD
        - name: MYSQL_DATABASE
          value: db_todo
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: 'mariadb:10.3.10'
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
            protocole: TCP
            name: mysqlport
        securityContext:
          privileged: false